In [27]:
from sklearn.datasets import fetch_20newsgroups
news=fetch_20newsgroups()

In [45]:
print(news.keys())

news.target

news.target_names

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [53]:
cats = ['alt.atheism', 'sci.space','comp.graphics','sci.med','soc.religion.christian','talk.politics.guns']
news_train = fetch_20newsgroups(subset ='train', categories=cats)
news_test = fetch_20newsgroups(subset= 'test', categories=cats)
print(news_train . keys( ))
print (news_train[ 'target_names'])

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
X_train_tf=count_vect.fit_transform(news_train.data)
print(X_train_tf)

X_train_tf.shape

  (0, 42931)	1
  (0, 13284)	1
  (0, 31301)	1
  (0, 41497)	1
  (0, 3748)	1
  (0, 23433)	1
  (0, 42163)	1
  (0, 19324)	1
  (0, 33519)	1
  (0, 32360)	1
  (0, 8132)	1
  (0, 25735)	1
  (0, 46913)	1
  (0, 18416)	1
  (0, 8383)	1
  (0, 10490)	2
  (0, 28343)	1
  (0, 17426)	1
  (0, 45188)	1
  (0, 28549)	1
  (0, 34558)	1
  (0, 49534)	2
  (0, 45533)	1
  (0, 26023)	1
  (0, 24015)	1
  :	:
  (3395, 23098)	1
  (3395, 38623)	1
  (3395, 40285)	1
  (3395, 8132)	2
  (3395, 46913)	1
  (3395, 33334)	7
  (3395, 44710)	1
  (3395, 21828)	1
  (3395, 45077)	6
  (3395, 41856)	1
  (3395, 30153)	1
  (3395, 26156)	2
  (3395, 44619)	11
  (3395, 49009)	1
  (3395, 8843)	1
  (3395, 24926)	4
  (3395, 23975)	1
  (3395, 35989)	1
  (3395, 32645)	1
  (3395, 28616)	1
  (3395, 27835)	1
  (3395, 33744)	1
  (3395, 37831)	1
  (3395, 43222)	1
  (3395, 21181)	2


(3396, 49848)

In [57]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer()
X_train_tfidf=tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape

(3396, 49848)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, news_train.target)

In [58]:
X_test_tf=count_vect.transform(news_test.data)
X_test_tfidf=tfidf_transformer.transform(X_test_tf)
predicted=clf.predict(X_test_tfidf)
predicted

array([2, 3, 1, ..., 5, 4, 4], dtype=int64)

In [59]:
from sklearn import metrics

In [60]:
from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(news_test.target,predicted))
print(metrics.confusion_matrix(news_test.target,predicted))

Accuracy 0.8526548672566372
[[183   1   7   4 115   9]
 [  1 337   2  11  30   8]
 [  2   7 310   8  61   8]
 [  0   4   4 358  20   8]
 [  2   1   1   4 390   0]
 [  0   1   1   3  10 349]]
